### ISSUE TITLE
Making distances callable

### ISSUE THREAD

**Issue by chethega** [JuliaStats/Distances.jl#109]
It would be nice if distances were callable, i.e. `(d::Metric)(x,y)=evaluate(d, x, y)`. Unfortunately this line does not fly, due to [https://github.com/JuliaLang/julia/issues/14919](https://github.com/JuliaLang/julia/issues/14919).

One could do `evaluate(d::Metric, x, y)=d(x,y)` and add the requisite definitions to the concrete metrics (that way, metric-space code using the old API would be compatible with both new and old API, and new-style distances would be compatible with both new-style and old-style distances).

Reason is that this would allow `Distances.jl` to be compatible with the "natural API" (the API everyone working with distances reinvents, where a distance is a function), without requiring `Distances.jl` as a dependency. I am pretty unsure whether `Metric<:Function` would be sensible.

**Comment by nalimilan** [comment]
I don't think JuliaLang/julia#14919 is a problem here. Since we already define convenience functions which call `evaluate`, we could also define `(::SomeDistance)(...) = ...` at the same time. Actually, we could even deprecate `evaluate`, which has no advantage over the standard call syntax AFAICT: it's most likely been introduced before one could make custom types callable.

**Comment by KristofferC** [comment]
Isn't it a bit inconsistent to use it with call overloading for single distance but as a first argument to `pairwise` and co?

**Comment by chethega** [comment]
>Isn't it a bit inconsistent to use it with call overloading for single distance but as a first argument to pairwise and co?

It is a bit inconsistent, and I don't really care for deprecating, i.e. `evaluate(d::Metric, x, y)= d(x,y)` should probably stay. 

My main consideration is to be compatible with the "natural API" which knows nothing about `pairwise` / `colwise` / etc, for metric-space algos that don't have `Distances.jl` as dependency. It just makes for a very nice documentation to say `dist(x,y)=norm(x-y); do_something(d, dataset)`, if `do_something` does not require additional structure on the metric (and yes, `Distances.jl` gives faster code + extra features like blas-based euclidean pairwise, and knn-trees, but sometimes clarity is more important than performance). Anything that dispatches on `Metric` is already requiring `Distances.jl` as dependency, so I see no reason to change any such code.

**Comment by KristofferC** [comment]
Done
