### ISSUE TITLE
Distances with missing values

### ISSUE THREAD

**Issue by bdeonovic** [JuliaStats/Distances.jl#11]
I saw this issue on DataFrames (https://github.com/JuliaStats/DataFrames.jl/issues/183), and noted that it was from a few years ago. Is there support for missing values in Distances.jl yet?

**Comment by johnmyleswhite** [comment]
No, there is not. Pull requests would be reviewed I'm sure, although I imagine that Distances.jl shouldn't depend upon DataArrays.

**Comment by lindahua** [comment]
I think supporting missing value is not in the scope of this package (at least at this point).

**Comment by oxinabox** [comment]
We should come back and do this now that Missing data handling is in Base.

**Comment by KristofferC** [comment]
There should be no need for special handling of Missing here.

Agreed with https://github.com/JuliaStats/Distances.jl/issues/11#issuecomment-100098293

**Comment by rofinn** [comment]
FWIW, I found a specific use case where supporting `missing`s here would help the larger ecosystem. Specifically, Distances.jl -> NearestNeighbors.jl -> Impute.jl.

https://github.com/invenia/Impute.jl/issues/141#issuecomment-1870734968

Impute.jl isn't getting a lot of active development anymore, so I understand if it isn't worth the change, but updating Distances.jl and NearestNeighbors.jl is the best approach.
