### ISSUE TITLE
Compatibility WeightedSqEuclidean with Tracker

### ISSUE THREAD

**Issue by theogf** [JuliaStats/Distances.jl#130]
When using `pairwise()` with a `WeightedSqEuclidean` metric, it is not possible to use Tracker.jl.
When computing the gradient the [`wsumsq_percol()`](https://github.com/JuliaStats/Distances.jl/blob/bb54e3b425d5804d4b5894e2d619a630e20c6873/src/common.jl#L112) function is problematic : 

```julia
function wsumsq_percol(w::AbstractArray{T1}, a::AbstractMatrix{T2}) where {T1, T2}
    m = size(a, 1)
    n = size(a, 2)
    T = typeof(one(T1) * one(T2))
    r = Vector{T}(undef, n)
    for j = 1:n
        aj = view(a, :, j)
        s = zero(T)
        @simd for i = 1:m
            @inbounds s += w[i] * abs2(aj[i])
        end
        r[j] = s
    end
    return r
end
```
`T1` will not be of type `TrackedReal{Float}` but `Float`, therefore `r` will be also `Float`. So the allocation `r[j] = s` fails since `s` is of type `TrackedReal`.
Changing `one(T1)` by `one(w[1])` solves the problem but is obviously not the best answer to the problem.

**Comment by nalimilan** [comment]
Maybe the loop could be switched to use an array comprehension instead?
