### ISSUE TITLE
Performance regression from 0.8.0 to 0.8.1

### ISSUE THREAD

**Issue by zhouyan** [JuliaStats/Distances.jl#144]
Given the following simple experiment

```
using Distances
x = randn(5000, 2000)
@time pairwise(CorrDist(), x, dims=2)
```

It takes 30 seconds on v0.8.1, and 0.1 seconds on v0.8.0

I am running a Julia 1.1.1 custom built with MKL on macOS 10.14.6

**Comment by KristofferC** [comment]
Woow... guess this was https://github.com/JuliaStats/Distances.jl/pull/139. Sigh, I'll look at it.

**Comment by zhouyan** [comment]
I am still trying to do some profiling to figure out why, but so far from what I see I believe you are right.

**Comment by KristofferC** [comment]
Can you try with https://github.com/JuliaStats/Distances.jl/pull/145.

**Comment by zhouyan** [comment]
Just tried, it restored the performance.
