### ISSUE TITLE
Distance between points a and b if the system is not perpendicular

### ISSUE THREAD

**Issue by programistawpf** [JuliaStats/Distances.jl#148]
Is it justified to calculate the distance between points a and b if the system is not perpendicular?
```
julia> a
2-element Array{Int64,1}:
 4
 3

julia> b
2-element Array{Int64,1}:
 2
 5

julia> rad2deg(acos(dot(a,b)/(norm(a)*norm(b))))
31.328692867804165

julia> Euclidean()(a,b)
2.8284271247461903
```
Paul

**Comment by KristofferC** [comment]
Yes, euclidean distance doesn't require that the two vectors are perpendicular.

**Comment by programistawpf** [comment]
![point_distances](https://user-images.githubusercontent.com/5564741/63654267-9917fd80-c778-11e9-99c9-3233c1baa2eb.png)
Red and black sytuations are another .... Are You shure ?

**Comment by KristofferC** [comment]
Yes, I'm sure. You seem to be confused about something. Maybe https://en.m.wikipedia.org/wiki/Euclidean_distance is useful reading.

**Comment by KristofferC** [comment]
And to use your picture, the distance is `sqrt((4-2)^2 + (5-3)^2) = sqrt(8) = 2.8284...` which i the same you got.

**Comment by programistawpf** [comment]
Thank for links, a kwnow Pitagoras  :)  But if axis are not ortogonal 
maybe a correction is needed some like this : cos((90-alfa)


sqrt(sum((cos((90-alfa)*pi/180.*(data2[i,:].-data2[j,:])).^2))

You can clearly see that the distance red blue are different :/
Paul

W dniu 2019-08-25 o 22:09, Kristoffer Carlsson pisze:
> And to use your picture, the distance is |sqrt((4-2)^2 + (5-3)^2) = 
> sqrt(8) = 2.8284...| which i the same you got.

**Comment by dkarrasch** [comment]
I think the OP was referring to the situation when the coordinate system is not orthogonal, in which case one needs a "generalized Euclidean distance" `sqrt((x-y)'G*(x-y))`, where `G` is the Gramian in the given coordinate system. In an orthonormal basis, `G` is the identity. I think `mahalanobis` should do the trick. In the README, `G` is called `Q` there and needs to be provided by the user.
