### ISSUE TITLE
pairwise for arrays of arrays

### ISSUE THREAD

**Issue by theogf** [JuliaStats/Distances.jl#152]
It would be nice to be able to be able to deal with arrays of arrays as well.
For example : 
```julia
A = [rand(3) for _ in 1:3]
P = pairwise(SqEuclidean(),A)
# Where pairwise(SqEuclidean(),hcat(A,...),dims=2) == P
```
In this case one could of course simply concatenate vectors, but for more complex objects (not necessarily real vectors) that would broaden the use of pairwise!
I could make a PR if you think that makes sense

**Comment by mkborregaard** [comment]
And please also Iterators and generators :-)

**Comment by yakir12** [comment]
+1 this would also allow for collections of `StaticVector`s (as in, coordinates).
