### ISSUE TITLE
Metric should be Pseudometric and description of SemiMetric is incomplete

### ISSUE THREAD

**Issue by IsakFalk** [JuliaStats/Distances.jl#153]
Looking at the `Distances.Metric` description it actually correspond to the mathematical notion of a [pseudometric](https://en.wikipedia.org/wiki/Metric_(mathematics)#Pseudometrics) and not a metric since it's missing the condition of d(x, y) = 0 implying that x = y. The same issue occurs with `Distances.SemiMetric` which is missing the same condition for it to actually correspond to the mathematical semimetric.

The reason why I bumped into this is that I'm trying to use  `Distances.jl` to define the [maximum mean discrepancy](https://en.wikipedia.org/wiki/Kernel_embedding_of_distributions) (MMD) which depends on a [kernel](https://en.wikipedia.org/wiki/Kernel_method). The MMD measures the "distance" between two distributions P and Q, but is only a metric if the underlying kernel is *characteristic*, otherwise it's a pseudometric.

**Comment by nalimilan** [comment]
Do you think this is just a problem with the documentation of `Metric`, or are there actually `Metric` subtypes in the packages which are actually pseudometrics?

**Comment by IsakFalk** [comment]
I haven't been able to go through and check all of the "distances" so I can't say for sure if there are any unweighted distance-like functions that are actually pseudometrics, but if any of the weighted ones are allowed to use a weight-vector with some entry equal to zero (and it seems like there is no restriction on these weights in terms of positivity but I might be wrong) then for example the Euclidean distance is not a metric. 

For example, let x, y, w in R^n where w is all ones except w_1 = 0, then all if x_i = y_i for all i > 1 but x_1 != y_1, then d(x, y) = 0, but x != y.

To be sure we'd probably have to go through the list of all distances and check on a case by case basis if the distance is a pseudometric unless some technical condition holds, such as with the MMD above.

**Comment by dkarrasch** [comment]
While this is a valid point at the conceptual level, I don't think it matters much given the current package ecosystem. These types are used for dispatch of methods. So, the hierarchy of metrics is used as follows: `SemiMetric`s assume symmetry, so when you compute mutual `pairwise` distances within a data set, you only compute one triangle of the square distance matrix, and copy it to the other triangle. `Metric`s assume the triangle inequality, which is useful for distance estimates as in `NearestNeighbors.jl`. There seems to be (currently) no use case that distinguishes whether the distance is a metric or a pseudometric. So, the question may be the other way around: in which use case would you leverage true metricity?

**Comment by nalimilan** [comment]
Yes, we should think in practical terms here. We could add a mention to the documentation about zero weights, but in practice "metric" sounds much more user-friendly than "pseudometric", so better keep that if that doesn't create issues.

**Comment by IsakFalk** [comment]
I agree as well, but would be good to just mention it briefly in the documentation / README.

**Comment by nalimilan** [comment]
Feel free to make a PR.

**Comment by dkarrasch** [comment]
Closed by #157.
