### ISSUE TITLE
Add MaximumMeanDiscrepancy distance

### ISSUE THREAD

**Issue by IsakFalk** [JuliaStats/Distances.jl#154]
The [maximum mean discrepancy](https://en.wikipedia.org/wiki/Kernel_embedding_of_distributions) is a pseudometric on distributions which uses [kernels](https://en.wikipedia.org/wiki/Kernel_method) (call this kernel K) to measure the distance between two distributions in a feature space. When the kernel is *characteristic* MMD is actually a metric. 

For general distribution the MMD is intractable, but if the distributions are convex combinations of dirac deltas, say $p = \sum_i^n a_i \delta_{x_i}, q = \sum_i^n b_i \delta_{y_i}$, then it reduces to $d(p, q) = \sum_{i, j}^{n} a_i a_j K(x_i, x_j) + \sum{l, t}^{m} b_l b_t K(y_l, y_t) - 2 \sum_{i, l}^{n, m} a_i b_l K(x_i, y_l)$ which is easily computed (for example by leveraging https://github.com/theogf/KernelFunctions.jl).

Finally, is `Distances.jl` the right place for this? I was a bit unsure but figured that it'd fit here as it has the Bregman divergence which is also a way to measure similarity between distributions.

**Comment by thomaspinder** [comment]
I think [IPMeasures.jl](https://github.com/aicenter/IPMeasures.jl) may already do this @IsakFalk

**Comment by dkarrasch** [comment]
@IsakFalk Can this be closed then?

**Comment by IsakFalk** [comment]
Yes, this can be closed.
