### ISSUE TITLE
What do you think of pairwise with DataFrame?

### ISSUE THREAD

**Issue by juliohm** [JuliaStats/Distances.jl#169]
I came into a recent scenario where I could be doing `pairwise(Euclidean(), df1, df2)`, but I am having to convert to matrix before calling pairwise `pairwise(Euclidean(), Matrix(df1), Matrix(df2)`. Would it make sense to support the Tables.jl API?

**Comment by KristofferC** [comment]
We don't want to add any dependencies to this package. It seems what you need it something that wraps a dataframe and makes it into an `AbstractMatrix`.

**Comment by juliohm** [comment]
Thank you. Just wanted to confirm before moving forward with this
direction. Feel free to close the issue. I'll close it when I reach my
computer.
