### ISSUE TITLE
[question] Edit distance applicable ?

### ISSUE THREAD

**Issue by johncwok** [JuliaStats/Distances.jl#175]
I made an implementation of the `edit` and `damerau-levenshtein` distance. They are measurements used to compute the "distance" (number of edits) between two strings and can generally also be applied to categorical data. Here is the implementation https://github.com/johncwok/EditDistance.jl
Do you think that it is applicable to this repo and that I should try to make a pull request ? Or is this repo strictly reserved for distances defined in the framework of vector spaces ?

**Comment by juliohm** [comment]
There are various package already for edit distance, are you aware of https://github.com/matthieugomez/StringDistances.jl ?

I also implemented edit distances for graphs in LightGraphs.jl: https://juliagraphs.org/LightGraphs.jl/stable/distance/#LightGraphs.edit_distance-Tuple{AbstractGraph,AbstractGraph}

So in my opinion, there are various packages already for edit distances that can be developed independently from the more widely adopted Distances.jl

**Comment by johncwok** [comment]
Oh I didn't know ... well this answers the question.
