### ISSUE TITLE
StaticMatrix with Mahalanobis

### ISSUE THREAD

**Issue by rmcaixeta** [JuliaStats/Distances.jl#181]
Hi

I'm trying to call Mahalanobis with a StaticMatrix and get the following:

```
ERROR: LoadError: MethodError: no method matching Distances.Mahalanobis(::StaticArrays.SArray{Tuple{2,2},Float64,2,4})
Closest candidates are:
  Distances.Mahalanobis(::Array{T,2}) where T
```

Would it be okay to open a PR to change the definition to something like that?

```julia
struct Mahalanobis{T} <: Metric
    qmat::AbstractMatrix{T}
end

struct SqMahalanobis{T} <: SemiMetric
    qmat::AbstractMatrix{T}
end
```

**Comment by juliohm** [comment]
You want the type to be concrete still @rmcaixeta , so the change should be:

```julia
struct Mahalanobis{M<:AbstractMatrix} <: Metric
    qmat::M
end
```
Julia will then figure out the exact type of `M`. Right now, when you write `qmat::AbstractMatrix` in the field, Julia will assume that you want the abstract type.

**Comment by rmcaixeta** [comment]
Thanks @juliohm 
Updating the PR in a few minutes
