### ISSUE TITLE
Implementing custom distance

### ISSUE THREAD

**Issue by ngiann** [JuliaStats/Distances.jl#183]
How do I go about implementing a new distance function? 

I tried to infer the interface by looking at metric.jl but I was quite confused.

As an example I tried to re-implement ```SqEuclidean```.

I searched for ```SqEuclidean``` and I saw that it is defined in metric.jl

In metric.jl I see that ```SqEuclidean``` appears only in a few places.
First there is a definition

```
struct SqEuclidean <: UnionSemiMetric
    thresh::Float64
end
.
.
.
SqEuclidean() = SqEuclidean(0)
```

and then further down follows the implementation:
```
# SqEuclidean
@inline eval_op(::SqEuclidean, ai, bi) = abs2(ai - bi)
sqeuclidean(a::AbstractArray, b::AbstractArray) = SqEuclidean()(a, b)
sqeuclidean(a::Number, b::Number) = SqEuclidean()(a, b)
```

To test my understanding, I just repeated all of the above with a new name i.e. prefixing everything with "test":
```

struct TestSqEuclidean <: Distances.UnionSemiMetric
    thresh::Float64
end

TestSqEuclidean() = TestSqEuclidean(0)


# TestSqEuclidean
@inline eval_op(::TestSqEuclidean, ai, bi) = abs2(ai - bi)
testsqeuclidean(a::AbstractArray, b::AbstractArray) = TestSqEuclidean()(a, b)
testsqeuclidean(a::Number, b::Number) = TestSqEuclidean()(a, b)
```

Unfortunately, I am clearly missing something important as the following is not working:

```
using Distances

a = randn(1,10);

# as expected:
SqEuclidean()(a,a)
0.0

# but for my definition:
TestSqEuclidean()(a,a)
```
I get the error ```ERROR: MethodError: objects of type TestSqEuclidean are not callable```.

Similarly:
```
# not shown, but produces 10 by 10 matrix as expected
pairwise(SqEuclidean(), a)

# but mine doesn't work:
pairwise(TestSqEuclidean(), a)
```
as I get the error ```ERROR: MethodError: no method matching eval_op(::TestSqEuclidean, ::Float64, ::Float64)```.

Clearly, internally the package ```Distances``` is making ```SqEuclidean``` callable and also ensures that pairwise can be called on it.

Obviously I am not fully implementing the required interface so that ```TestSqEuclidean```  is a valid distance.
Could someone please explain to me what is missing?

ps. I also had a look at the package [SpectralDistances.jl](https://baggepinnen.github.io/SpectralDistances.jl/latest/distances/) but unfortunately I still couldn't figure this out.

**Comment by enuit** [comment]
Hey, I recently had the same Problem. I can partially help you. 
I don't understand why it doesn't work, however, I fiddled myself around it:
```julia
begin
	
	struct TestSqEuclidean <: Distances.UnionSemiMetric
	    thresh::Float64
	end
	
	TestSqEuclidean() = TestSqEuclidean(0)
	
	
	# TestSqEuclidean
	@inline (::TestSqEuclidean)(ai, bi) = abs2(ai - bi)
	testsqeuclidean(a::AbstractArray, b::AbstractArray) = TestSqEuclidean()(a, b)
	testsqeuclidean(a::Number, b::Number) = TestSqEuclidean()(a, b)
end
```
works for me.
I replaced 
`    @inline eval_op(::TestSqEuclidean, ai, bi) = abs2(ai - bi)`
with
`    @inline (::TestSqEuclidean)(ai, bi) = abs2(ai - bi)`
and that was it. 


By making it a subtype Metric, I was able to use it with the NearestNeighbors.jl Package:
```julia
import Distances
import NearestNeighbors

begin
	struct TestSqEuclidean <: Distances.Metric
	    thresh::Float64
	end
	
	TestSqEuclidean() = TestSqEuclidean(0)
	
	
	# TestSqEuclidean
	@inline (::TestSqEuclidean)(ai, bi) = sqrt(sum((ai .- bi).^2))
	testsqeuclidean(a::AbstractArray, b::AbstractArray) = TestSqEuclidean()(a, b)
	testsqeuclidean(a::Number, b::Number) = TestSqEuclidean()(a, b)
end

NearestNeighbors.BallTree(rand(10,3), TestSqEuclidean())
```

Anyway your question helped me a lot in building that measure so thank you :)

**Comment by dkarrasch** [comment]
In the OP, there was no definition given to `TestSqEuclidean()(a,a)`, so that's why it's complaining about a missing method. This is fixed in @enuit's answer by the line
```julia
@inline (::TestSqEuclidean)(ai, bi) = sqrt(sum((ai .- bi).^2))
```
which makes any instance of `TestSqEuclidean` callable. To learn how to write a new distance type, I'd start from a different code file that defines a single distance, like `haversine.jl`. In `metrics.jl`, an entire class of metrics is defined, satisfying a specific interface. That's way harder to understand at first reading.

**Comment by ngiann** [comment]
Thanks both of you for your replies.

@dkarrasch: you are absolutely right of course pointing out the missing method. Also, thanks for the useful suggestion for starting off with a simpler distance metric. However, I am still puzzled at how ```SqEuclidean``` is implemented. I can't seem to find a definition similar to the one you suggest for my test case, i.e.
```
@inline (::SqEuclidean)(ai, bi) = sqrt(sum((ai .- bi).^2))
```
Not finding such a definition in the code, lead me to believe that I may not need one for my ```TestSqEuclidean``` example.

**Comment by dkarrasch** [comment]
It's indeed quite hidden:

https://github.com/JuliaStats/Distances.jl/blob/068f820f960a55fa81d2dc361042c513e38eae80/src/metrics.jl#L298-L303

**Comment by ngiann** [comment]
Thanks for your help, it is now completely clear to me!

**Comment by FedeClaudi** [comment]
Hello, 

Sorry to resurrect this old issue.
I just wanted to chime in and say that it can indeed be hard to figure out how to define custom distance types for new users (like myself).  I think with this issue's conversation I have all the info I need, but it would be a very valuable addition to the documentation to have a small section outlining the steps required to implement a custom distance type working with `Distances.jl` interface.

Either way, thank you so much for this package, it's super useful!
