### ISSUE TITLE
Why different performance in this case?

### ISSUE THREAD

**Issue by AhmedSalih3d** [JuliaStats/Distances.jl#186]
Hello!

I have posted a question on Discourse, which might be a bit too "detail-oriented", i.e. only relevant for this package:

https://discourse.julialang.org/t/understanding-why-one-function-is-faster-than-the-other/48866 

My basic findings are that code producing the same @code_llvm results runs at different speeds. "colwise" is 4x faster than my "calc_euclidean". All details are in the discourse post - I just wanted to  post it here in case it would not get attention on discourse 

I am trying to learn to optimize calculations etc., so I would hope one of you would take a look at it. I hope I have not done a "dumb mistake", but I am just interested in learning.

Kind regards

**Comment by nalimilan** [comment]
So IIUC this package is faster than your code? Then please don't file an issue against this package.

**Comment by AhmedSalih3d** [comment]
I think you misunderstood my intent. I was just curious about why there was a difference in performance, and was afraid that my question might have been too "specific" to get a proper answer, so a while after I just wanted to ask here. I got my answer on Discourse though, so all is fine

Kind regards - thanks for your time
