### ISSUE TITLE
`result_type` acts on objects for arrays but on types otherwise

### ISSUE THREAD

**Issue by ericphanson** [JuliaStats/Distances.jl#190]
https://github.com/JuliaStats/Distances.jl/blob/f97709ff6e04fc290dd090cd0e541d7b9b052475/src/generic.jl#L29-L30

This seems a bit inconsistent, because it makes it hard to use `result_type` in generic code where you could be computing distances between arrays or between scalars. Maybe a fallback like `result_type(metric, a::Number, b::Number) = result_type(metric, typeof(a), typeof(b))` could be added?

I can make a PR if this is acceptable.

**Comment by dkarrasch** [comment]
I guess there is no such fallback currently because for distances between numbers, you don't need to determine the result type beforehand, you just compute that number and "observe" the type. You don't need to allocate matrices, and you don't have to handle empty arrays to return the correct `zero`. To me, the proposal sounds good, but I'd be curious what you need `result_type` for in generic code.

**Comment by johnnychen94** [comment]
Similar to #185, I think it's a good change to let other packages reuse the `result_type` tool. Just need to get some consensus here.

**Comment by ericphanson** [comment]
@dkarrasch my use case is the following. NearestNeighborDescent.jl uses `result_type` here:

https://github.com/dillondaudert/NearestNeighborDescent.jl/blob/fa8d325ba4ebd754843353b04942355a824a5f02/src/knn_graph/heap_graph.jl#L60

NearestNeighborDescent is used in [UMAP.jl](https://github.com/dillondaudert/UMAP.jl) for finding the $k$-nearest neighbors to a given point. Usually these points are vectors, and everything works fine. However, I'm working on extending UMAP.jl to allow multiple "views" of the data (say, the usual vectors and then also a scalar quantity that describes something else about the points). E.g. in MNIST digit classification example, the images of the numbers are represented as vectors, but we could also look at giving UMAP the numbers themselves (or e.g. some of the numbers). In this case, we also need to find the $m$-nearest neighbors and ideally can follow the same code path, except now we have scalars instead of vectors.

johnnychen94 #185 looks useful to me too; IMO type constraints should be used just for dispatch, and it's not clear why subtyping premetric should be a requirement (what if you want to subtype something else?).

**Comment by johnnychen94** [comment]
@ericphanson I'm currently rushing for some dues so feel free to work on top of that.
