### ISSUE TITLE
Colwise and pairwise can return incorrect distances

### ISSUE THREAD

**Issue by yurivish** [JuliaStats/Distances.jl#206]
Due to improper use of `@inbounds`, the `colwise` function can nondeterministically return incorrect results when used on arrays with offset axes due to out-of-bounds memory accesses.

```julia
julia> using Distances, OffsetArrays

julia> test_colwise() = sum(
               colwise(
                       Euclidean(),
                       OffsetArray(ones(11, 11), -5:5, -5:5),     # matrix of 1.0
                       OffsetArray(2 .* ones(11, 11), -5:5, -5:5) # matrix of 2.0
               )
       )
test_colwise (generic function with 1 method)

julia> [test_colwise() for _ in 1:10]
10-element Array{Float64,1}:
  Inf
  Inf
  Inf
 NaN
  32.49537442426318
  32.49537442426318
  32.49537442426318
  32.49537442426318
  32.49537442426318
  32.49537442426318
```

https://github.com/JuliaStats/Distances.jl/blob/23b0023cd5129c9e692a557904df1f1ec9088a05/src/generic.jl#L61

https://github.com/JuliaStats/Distances.jl/blob/23b0023cd5129c9e692a557904df1f1ec9088a05/src/generic.jl#L71

https://github.com/JuliaStats/Distances.jl/blob/23b0023cd5129c9e692a557904df1f1ec9088a05/src/generic.jl#L81

https://github.com/JuliaStats/Distances.jl/blob/23b0023cd5129c9e692a557904df1f1ec9088a05/src/generic.jl#L81

It looks like the same issue exists with `pairwise` defined in the same file.

https://github.com/JuliaStats/Distances.jl/blob/23b0023cd5129c9e692a557904df1f1ec9088a05/src/generic.jl#L173

https://github.com/JuliaStats/Distances.jl/blob/23b0023cd5129c9e692a557904df1f1ec9088a05/src/generic.jl#L173

https://github.com/JuliaStats/Distances.jl/blob/23b0023cd5129c9e692a557904df1f1ec9088a05/src/generic.jl#L198

https://github.com/JuliaStats/Distances.jl/blob/23b0023cd5129c9e692a557904df1f1ec9088a05/src/generic.jl#L214

**Comment by dkarrasch** [comment]
This is "fixed" on `master`, in that it throws because it (correctly) requires one-based indexing. 😅 If you're on Julia v1.1+, you could replace the `colwise` call by
```julia
map(Euclidean(), eachcol(OffsetArray(ones(11, 11), -5:5, -5:5)),     # matrix of 1.0
                             eachcol(OffsetArray(2 .* ones(11, 11), -5:5, -5:5)) # matrix of 2.
    )
```
or, starting from the upcoming release,
```julia
colwise(Euclidean(),
    eachcol(OffsetArray(ones(11, 11), -5:5, -5:5)),     # matrix of 1.0
    eachcol(OffsetArray(2 .* ones(11, 11), -5:5, -5:5)) # matrix of 2.
    )
```
The first call will yield an OffsetArray, the second will be returning a standard one-based vector.
