### ISSUE TITLE
Create distance matrix function

### ISSUE THREAD

**Issue by PeetoomHeida** [JuliaStats/Distances.jl#214]
Perhaps this request won't fit well in the scope of the project, but I have yet to identify a more suitable package. Please point me in the direction of one if you know it. 

It would be great if we could have a way to calculate a distance matrix for all entries within a vector/tuple/array. A basic implementation on an ```n-by-2``` array would be:
```
julia>foo = rand(10,2)

julia>function distance_calc(x)
    output_dim = length(x[: ,1]) #finds size of output Array
    dist_matrix = Array{Float64}(undef, output_dim, output_dim)
    for i in 1:lastindex(x[:,1])
        for j in 1:lastindex(x[:,1])            
            dist_matrix[i,j] = sqrt((x[i,1]-x[j,1])^2 + (x[i,2]-x[j,2])^2)
        end
    end
    return dist_matrix
end

julia>my_dist_matrix = distance_calc(foo)
julia>my_dist_matrix
10×10 Array{Float64,2}:
 0.0       0.803376  0.764539  0.979535  0.631775  1.22287   0.471997  0.647222  0.554386  0.576429
 0.803376  0.0       0.276699  0.540599  0.593389  0.45538   0.505215  0.257311  0.63174   0.297312
 0.764539  0.276699  0.0       0.809662  0.779795  0.68334   0.336668  0.126373  0.791024  0.454933
 0.979535  0.540599  0.809662  0.0       0.393897  0.503401  0.927019  0.748202  0.484155  0.461893
 ⋮                                                 ⋮
 0.647222  0.257311  0.126373  0.748202  0.671199  0.706002  0.258301  0.0       0.675249  0.349397
 0.554386  0.63174   0.791024  0.484155  0.090701  0.88563   0.713182  0.675249  0.0       0.343925
 0.576429  0.297312  0.454933  0.461893  0.32489   0.652327  0.471489  0.349397  0.343925  0.0
```

I'm sure there is a more efficient way to implement the function. I am fairly new to the language (coming from R), so any feedback on this idea is welcome!

Cheers

**Comment by arvganesh** [comment]
I'm somewhat new to this package, but have you seen [this](https://github.com/JuliaStats/Distances.jl#computing-distances-between-corresponding-objects-column-wise)? I think it does something similar to what you're looking for.

**Comment by juliohm** [comment]
@PeetoomHeida you probably want to ask these questions in the forums before opening an issue. You seem to be asking for an existing feature. Have you tried `pairwise` from the README?

**Comment by PeetoomHeida** [comment]
@juliohm  Sorry about that. I can move this over to the forums.
Similar to the question in issue #138 I am hoping to have a function that calculates the distance between rows returning an ```n-by-n``` matrix of distances. 

```
julia>foo = rand(10,2)
julia>dist = pairwise(Euclidean, foo, foo)
2×2 Array{Float64,2}:
 0.0       0.912117
 0.912117  0.0
```
 Pairwise seems to only return an ```m-by-m``` matrix, which summarizes the distance between the entire column, rather than between each entry in the column. Re-reading the README it seems like the scope of this package is only interested in distances between entire vectors. My guess is that this feature is better suited somewhere else.

**Comment by juliohm** [comment]
If you want distances between scalar entries of a matrix, you can use Julia broadcast:

```julia
julia> A = rand(3,3)
3×3 Matrix{Float64}:
 0.755214  0.984019   0.707174
 0.854456  0.518774   0.460463
 0.76256   0.0419187  0.714334

julia> B = rand(3,3)
3×3 Matrix{Float64}:
 0.407927  0.612406  0.245337
 0.350075  0.513371  0.639821
 0.526297  0.46636   0.0851331

julia> evaluate.(Ref(Euclidean()), A, B)
3×3 Matrix{Float64}:
 0.347287  0.371613    0.461837
 0.504381  0.00540383  0.179358
 0.236263  0.424441    0.629201
```

Please close the issue and try to get support on the forums instead if the above code does not address your use case.
