### ISSUE TITLE
Why single precision by default in Haversine?

### ISSUE THREAD

**Issue by juliohm** [JuliaStats/Distances.jl#216]
https://github.com/JuliaStats/Distances.jl/blob/369f58632f76ea02922c894bf50162206b24a41f/src/haversine.jl#L14

Most lat/lon datasets are double precision so I don't understand why the single precision here. Can we double it?

**Comment by nalimilan** [comment]
See https://github.com/JuliaStats/Distances.jl/pull/176#discussion_r541371211. The idea was that if you have `Float64` inputs, the result with be promoted to `Float64`, but if you have lower precision inputs they will keep using `Float32`. What's your use case?

**Comment by juliohm** [comment]
lat/lon values are stored as Float64 in most GIS datasets. Computing anything in single precision is pretty rare because lat/lon values differ in the very last digits of the double precision representation. That is why I got confused with Float32.

This internal design decision could be made explicit in the docstring so that end users coming from GIS won't question it again. I did a quick benchmark to see if the promotion from single to double precision changed the performance, but apparently it doesn't.

**Comment by juliohm** [comment]
If we talk about the most common use case of the Haversine, it will be in GIS applications. And in this case I would just set the default to Float64 to avoid confusion. People interested in Haversine for other exotic uses like GPU for example, could explicitly provide other type parameter.

**Comment by nalimilan** [comment]
Do you have a concrete example where this could be confusing?

@mkborregaard @dkarrasch What do you think?

**Comment by juliohm** [comment]
Just instantiating the distance will show the type parameter in the REPL and this is confusing for someone expecting double precision by default.

**Comment by dkarrasch** [comment]
I believe that having a "minimal" type here is (at the risk of human confusion) the better choice. There is no lack of precision for that number, and for higher-precision floats it will be promoted anyway. To me personally, it feels a bit like the `I` in `LinearAlgebra`, whose default type is `Bool` for the same reason. It would be a different story if performance was suffering, though. Then we should perhaps take care of the most common use case.

**Comment by juliohm** [comment]
Thank you, I think it makes sense given that there is no performance penalty.

Perhaps a note in the docstring would be enough.

**Comment by nalimilan** [comment]
See https://github.com/JuliaStats/Distances.jl/pull/226#discussion_r679439667: it turns out we can just use an `Int` value as the default.

**Comment by mkborregaard** [comment]
great!
