### ISSUE TITLE
Hausdorff distance

### ISSUE THREAD

**Issue by juliohm** [JuliaStats/Distances.jl#23]
I want to make the [Hausdorff distance](https://en.wikipedia.org/wiki/Hausdorff_distance) available in Julia. Is the `Distances.jl` package a good fit?

I can think of a very simple (naive) implementation that works surprisingly well:

```julia
using Distances

A, B # matrices which columns represent the points in the pointset
D = pairwise(Euclidean(), A, B)
daB = maximum(minimum(D,2))
dbA = maximum(minimum(D,1))
result = max(daB, dbA)
```

**Comment by juliohm** [comment]
I want to write it as a separate function following some of the ideas on this paper: http://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=7053955

What is the best place to add this function in the package? I would say it fits side by side with functions like pairwise() where we are given two sets of vectors, but it's not as generic as pairwise to be considered part of generic.jl.

**Comment by rawls238** [comment]
not a maintainer of this package, but I think it would be great to add the Hausdorff distance into this package

**Comment by juliohm** [comment]
I was thinking about it and it seems to me that this function should be part of a more specific package like `Images.jl`. I'll open an issue there, closing this one.

**Comment by juliohm** [comment]
To anyone interested, the issue is linked: https://github.com/timholy/Images.jl/issues/420
