### ISSUE TITLE
Distance between vector and each row of a matrix

### ISSUE THREAD

**Issue by mroavi** [JuliaStats/Distances.jl#241]
It is mentioned in the README that:

> Note that either of X and Y can be just a single vector -- then the `colwise` function computes the distance between this vector and each column of the other argument.

Is there a way to compute the distance between a vector and each **row** of the other argument?

**Comment by dkarrasch** [comment]
You could do, for instance,

```julia
map(b -> Euclidean()(a, b), eachrow(B))
```

for `a` the vector and `B` the matrix whose rows you're interested in. We do have a couple of iterator-based methods, so another "fancy" way of doing it could be:

```julia
colwise!(r, Euclidean(), Iterators.repeated(a, size(B, 1)), eachrow(B))
```

In some sense, use of `eachrow` and `eachcol` is advantageous, because you have clear control over what should be computed.

**Comment by mroavi** [comment]
Thanks for the answer @dkarrasch. I have a follow-up question:

In the code below, `points` is a 2 by N `Matrix`, and `means` is a 2 by 3 `Matrix`.
The following code computes the squared distance from each column in the `points` matrix to each column in the `means` matrix.
 
```julia
# Find the squared distance from each column in the points matrix to each colmun in the means matrix
points = rand(2, 10)
means = rand(2,3)
d = pairwise(SqEuclidean(), points, means, dims=2)
```

But now suppose that my data is arranged in rows rather than cols, e.g.:
```julia
points = rand(2, 10)
means = rand(2,3)
```
Could I use the approach above (the pairwise function) to compute the squared distance from each row in the `points` matrix to each row in the `means` matrix?

**Comment by dkarrasch** [comment]
I guess you (still) have the dimensions wrong, but generally you should only need to change the `dims = 1` argument. For questions regarding usage it is best to post on https://discourse.julialang.org/. You'll get help much faster and also from other users, while the issues here are mostly only read by developers.
