### ISSUE TITLE
Inconsistent results with copy of  transpose matrix 

### ISSUE THREAD

**Issue by timze216** [JuliaStats/Distances.jl#243]
Thanks for this helpful packages.  I found it gets Inconsistent results when the input is a copy of  transposed matrix.  (Distances.jl  v0.10.7 )

A mini demo code to reproduce is as below:  
```julia 
using Distances
Random.seed!(1234);
df = rand(13,3)';  #  transpoed  matrix 
df2,df3,df4,df5,df6 = df,copy(df),copy(df),deepcopy(df),Array(df)

f(x) = pairwise(Euclidean(), x, dims=2)

@info df == df2, f(df) == f(df2)
@info df == df3, f(df) == f(df3)
@info df == df4, f(df) == f(df4)
@info df == df5, f(df) == f(df5)
@info df == df6, f(df) == f(df6)

@info df2 == df3, f(df2) == f(df3)

#[ Info: (true, true)
#[ Info: (true, false)
#[ Info: (true, false)
#[ Info: (true, true)
#[ Info: (true, false)
#[ Info: (true, true)
``` 
Not sure if it is related to shallow copy behavior or  Distances.jl.

**Comment by dkarrasch** [comment]
They are equal essentially up to numerical precision, though:

```julia
using Test
@test f(df) ≈ f(df2) rtol=2eps()
@test f(df) ≈ f(df3) rtol=2eps()
@test f(df) ≈ f(df4) rtol=2eps()
@test f(df) ≈ f(df5) rtol=2eps()
@test f(df) ≈ f(df6) rtol=2eps()
```

I think this is an artifact of which multiplication BLAS-routine exactly is used in the background: 

https://github.com/JuliaStats/Distances.jl/blob/aae27b251039e655654a005588af492e2ed2ee1b/src/metrics.jl#L703-L708
