### ISSUE TITLE
supertypes of minkowski and mahalanobis do not match most other classes

### ISSUE THREAD

**Issue by CMGreenspon** [JuliaStats/Distances.jl#245]
```
julia> supertypes(typeof(euclidean))
(Euclidean, Distances.UnionMetric, Metric, SemiMetric, PreMetric, Any)

julia> supertypes(typeof(minkowski))
(typeof(minkowski), Function, Any)

julia> supertypes(typeof(mahalanobis))
(typeof(mahalanobis), Function, Any)
```

Easy to get around this when trying to quickly switch between distance metrics but it seems like odd behavior

**Comment by richardreeve** [comment]
I think the fact that most of the shorthand distance functions (like `euclidean()`) give supertypes at all is a "feature" of how the functions are defined here:

https://github.com/JuliaStats/Distances.jl/blob/6d0110dbdd7b94ea663e58479ce3a6564078c21e/src/metrics.jl#L328

The actual type hierarchy can be derived from the types themselves, which are capitalised as `Euclidean`, `Mahalanobis` and `Minkowski`, etc:

```
julia> supertypes(Euclidean)
(Euclidean, Distances.UnionMetric, Metric, SemiMetric, PreMetric, Any)

julia> supertypes(Mahalanobis)
(Mahalanobis, Metric, SemiMetric, PreMetric, Any)

julia> supertypes(Minkowski)
(Minkowski, Distances.UnionMetric, Metric, SemiMetric, PreMetric, Any)
```
