### ISSUE TITLE
kl_divergence and js_divergence do not propagate NaNs

### ISSUE THREAD

**Issue by mauricelanghinrichs** [JuliaStats/Distances.jl#259]
I noticed the following behaviour for the distribution-based KL and JS distances. In contrast to `euclidean` as a reference, `kl_divergence` and `js_divergence` distances do not propagate `NaN`s, leading to negative distances in the examples below. I don't know if this is desired behaviour; in my opinion they should rather propagate `NaN`s instead.

```julia
julia> using Distances
julia> kl_divergence([NaN, 0.1], [0.5, 0.5])
-0.16094379124341004
```

```julia
julia> js_divergence([NaN, 0.1], [0.5, 0.5])
-0.10051100363189411
```

```julia
julia> euclidean([NaN, 0.1], [0.5, 0.5])
NaN
```

**Comment by richardreeve** [comment]
@devmotion - #260 closes this as well as some other minor testing fixes. Could you check it and merge it if you're happy?
