### ISSUE TITLE
Is distributed computing available on this package?

### ISSUE THREAD

**Issue by WuSiren** [JuliaStats/Distances.jl#263]
If there are multiple worker processes, will this package take advantage of distributed computing automatically? For example,
``` julia
using Dsitributed
@everywhere using Distances
X = rand(3,10)
Y = rand(3, 20)
pairwise(Euclidean(), X, Y, dims=2)
```

**Comment by dkarrasch** [comment]
No, it isn't. `pairwise(Euclidean(), ...)` uses matrix multiplication though, so potentially multithreading via BLAS.
