### ISSUE TITLE
Would it make sense to move StatsBase's distances/divergences here?

### ISSUE THREAD

**Issue by ararslan** [JuliaStats/Distances.jl#45]
Currently StatsBase defines the L2, squared L2, L1, and L-inf distances, as well as the generalized Kullback-Leibler divergence, and the mean absolute, max absolute, mean squared, and root mean squared deviations. It seems to me that those may be better served in a package dedicated to distance metrics such as this one, particularly since other functions in StatsBase don't appear to rely on them. Thoughts?

**Comment by ararslan** [comment]
Wow, the amount of feedback here is overwhelming. Not all at once, now! 😜

**Comment by kmsquire** [comment]
@ararslan, it's mostly the case that JuliaStats has a dearth of developers, and no one has really taken responsibility for this package recently. 

To me, your proposal makes sense. It would be good to know how many (and which) packages use any of those functions, and to be sure there's a good plan to deprecate them. 

If no one else responds here soon, can you open a separate issue at StatsBase?  Shouldn't really be necessary, since most of the same developers will be reading both, but since that is the core stats package, there might be a stronger response.

**Comment by nalimilan** [comment]
Makes sense to me too. They feel a bit lonely in StatsBase.

**Comment by ararslan** [comment]
I'd be more than happy to help out with JuliaStats stuff if active devs are scarce!

Do you know of a good way to go about determining which packages rely on the StatsBase distance functions? Deprecating them could be done in a similar manner to the prime number functions in base Julia, for which the deprecation message says to use the Primes package. In this case, it could be as simple as s/Primes/Distances/ and figuring out how long we want to keep them deprecated before removing them.

Sure, if no one else responds soon I'll open an issue on StatsBase.

**Comment by nalimilan** [comment]
It's a good idea to deprecate them anyway, as private code can rely on them. The general principle is that deprecations are only removed in the next major version (or before `1.0`, when bumping the minor version number). See `base/deprecated.jl` in Julia Base about that process.

**Comment by ararslan** [comment]
Thanks for the info about the deprecation process @nalimilan, that's really helpful!

**Comment by KristofferC** [comment]
More distances in `Distances.jl` sounds good to me.

**Comment by richardreeve** [comment]
@ararslan I think it would definitely make sense to combine them in one place. I suggested a while ago to add Rényi entropies and divergences (generalisations of entropy and Kullback-Leibler divergence) as well in [StatsBase#131](https://github.com/JuliaStats/StatsBase.jl/issues/131) without response, and I'd still be happy to do that, as I would find it useful to have them somewhere standard.

**Comment by ararslan** [comment]
@richardreeve Sounds good to me. Want to submit a PR here for the divergences and StatsBase for the entropies?

**Comment by richardreeve** [comment]
@ararslan Okay. Is there a policy about non-ascii characters - i.e. should I be creating Rényi divergences or Renyi divergences?

**Comment by ararslan** [comment]
I don't know of any actually policy about it, but what I would do personally would be to mirror what we did in StatsBase for R-squared: have the ASCII version `r2` but define `const r² = r2`. That way people can use either.

**Comment by richardreeve** [comment]
Okay. Will do.

**Comment by johnmyleswhite** [comment]
I would encourage not defining `rényi`.

**Comment by ararslan** [comment]
The best advice I can give is that if @johnmyleswhite says something different than what I said, you should trust his judgement over mine.

**Comment by richardreeve** [comment]
That's a pity... personally, I don't have any non-ascii characters in my name, but I've always felt it's a shame now we have unicode that we still choose to misspell things, though I understand the problem with homoglyphs in particular. Anyway, I'll drop the `rényientropy`, `rényidivergence` and `wrényi`.

More generally though, I have to admit I am particularly fond of finally being able to use unicode in my variable names, as it's always been annoying not to have greek letters in particular accessible to me - writing beta when we have a perfectly good symbol β for it seems unhelpful... one of the minor things I like about julia is the existence of ≈ as an alias for isapprox(), and other similar features, and this seemed to be an extension of that theme.

**Comment by johnmyleswhite** [comment]
I think the core design principles are (a) the official API must never use Unicode and (b) we should export as few things as possible. I think the concern about misspelling things is a little bit roman-letter-centric: we wouldn't start using variable names like `Πλατων`, let alone something like `毛澤東`.

**Comment by richardreeve** [comment]
Okay, thanks for clarifying. I will stick to that. As I said above though, symbols like ≈ are exported and are unicode, and I confess I think that's a good thing and should be encouraged _where appropriate_.
```{julia}
if a ≈ 1.0
  ...
end
```
just seems clearer in intent to me (modulo the ability to check exactly what it means with `?≈`, just as I would with `?isapprox`) than:
```{julia}
if isapprox(a, 1.0)
  ...
end
```
