### ISSUE TITLE
cosine distance formula

### ISSUE THREAD

**Issue by missperovaz** [JuliaStats/Distances.jl#47]
In your documentation, you mention that the cosine distance is calculate as:

1 - dot(x, y) / (norm(x) * norm(y))

However, I think that the correct expression would be 

vecdot(x, y) / (norm(x) * norm(y))

Is it accurate?

Thanks

**Comment by johnmyleswhite** [comment]
I believe that's cosine similarity since it increases monotonically as the vectors get closer in angular distance.

**Comment by missperovaz** [comment]
Any reason to change the 'wording'? or the formula? There are other items in the package that are not distances per se, i.e. divergence

**Comment by missperovaz** [comment]
Also,

cosine_dist([1.0 1.0]',[-1.0 -1.0]') 
gives approx -2

vecdot([1.0 1.0]',[-1.0 -1.0]')/(norm([1.0 1.0]')*norm([1.0 1.0]'))
gives approx -1

cosine distance as -1 for vectors with opposite directions makes sense for me... should the similarity be 0 instead or I'm missing the concept?

**Comment by KristofferC** [comment]
https://reference.wolfram.com/language/ref/CosineDistance.html agrees with 1 - u . v / (|u||v|)

For similarity, the similarity is 0 if the vectors are orthogonal, +1 if parallel and -1 if opposite.

Closing this, please post if there is anything further that should be done.

**Comment by mirestrepo** [comment]
I see two problems with current implementation of the distance
```
function eval_end(::CosineDist, s)
    ab, a2, b2 = s
    max(1 - ab / (sqrt(a2) * sqrt(b2)), zero(eltype(ab)))
end
```
1. If there are negatives in the vector, their cosine similarity can be negative and the distance becomes greater than 1!
2. When is 1 - ab / (sqrt(a2) * sqrt(b2)) smaller than 0? Why taking the max? 
 -1 <= ab / (sqrt(a2) * sqrt(b2) <=1

Wikipedia (not that it should trusted more than Wolfram - but I think the discussion makes sense) suggests distance = arccos(similarity)/pi

https://en.wikipedia.org/wiki/Cosine_similarity

Wich will handle the sign appropriately. Currently with negative vectors I'm getting a cosine distance greater than 1 - also

**Comment by mirestrepo** [comment]
Maybe I'm wrong ... I was thinking cosine distances should be between [0,1] ... but they are between [0,2]

Maybe this can be clarified the in the documentation? There could be another column on the readme distance table specifying the range of the distance functions
