### ISSUE TITLE
Please tag latest version in METADATA

### ISSUE THREAD

**Issue by davidavdav** [JuliaStats/Distances.jl#50]
I am maintaining GaussianMixtures, which depends on Clustering, which depends on Distances.  Because julia-0.5 warnings are extremely slow, my GaussianMixtures tests never end because of a deprecation warning that has already been solved in #48 . 

This problem would be solved if Distances tags https://github.com/JuliaStats/Distances.jl/commit/152d6cca0abdee1a3a4ead3a43fb1437b17a16f8 as a new minor version in METADATA.  Then I can get GaussianMixtures [up to date with julia v0.5](https://github.com/davidavdav/GaussianMixtures.jl/issues/19). 

Thanks.

**Comment by KristofferC** [comment]
Will do it today.

**Comment by ranjanan** [comment]
+1
