### ISSUE TITLE
Feature Request: evaluate pairwise distances on subset of columns indexed by a vector

### ISSUE THREAD

**Issue by gasagna** [JuliaStats/Distances.jl#52]
Hi, 

I have a "large" dataset and I would like to calculate the pairwise distances only on a  subset of the columns, indexed by a vector of Ints. The obvious thing to do is to code up the double loop explicitly myself but I though It might be a useful feature to have in the package itself.

How hard would it be to implement it thoughout the package?

**Comment by jiahao** [comment]
Is what you are asking for different from something like

```jl

Asub = sub(A, :, 1:10) #First ten columns of A
Bsub = sub(B, :, 101:110) #Ten more columns of B
renyi_divergence(Asub, Bsub, 2)
```

?

**Comment by gasagna** [comment]
It is exactly this, thanks. Just did not come to my mind that I could use views!
