### ISSUE TITLE
Need for custom floating point precision due to memory constraints

### ISSUE THREAD

**Issue by juliohm** [JuliaStats/Distances.jl#57]
I am making use of `pairwise(Euclidean(), X, Y)` with `size(X,2) = size(Y,2) ~= 50000`. It seems that the current implementation always sets the `result_type` to `Float64`: https://github.com/JuliaStats/Distances.jl/blob/master/src/generic.jl#L27

My workstation has 8GB of RAM and therefore I cannot proceed with such precision. Could you please consider adding an option for custom result types? `Float16` would solve the problem.

Thank you.

**Comment by KristofferC** [comment]
I would have thought https://github.com/JuliaStats/Distances.jl/blob/f6cee365488526427b54a4d7cbd3d5022d4d59c1/src/metrics.jl#L85 would override it?

**Comment by juliohm** [comment]
Indeed @KristofferC, I had a typo in my test case. If I set the types of `X` and `Y` to be arrays of `Float16` I don't go out of memory. Closing the issue.
