### ISSUE TITLE
How to cite license

### ISSUE THREAD

**Issue by robertdj** [JuliaStats/Distances.jl#62]
I'm reusing ideas from *Distances*' type system and `evalute` function to make norms, i.e., essentially distances of one argument instead of two.
As such, I think it's appropriate that I cite *Distances*' license somewhere, but I'm unsure of the location.

- Should it be in the `LICENSE.md` of my package?
- Mentioned somewhere in the `README` of my package`?
- Be included in the file where my `evaluate` method is?

**Comment by nalimilan** [comment]
You just need to include the terms of the MIT license in your `LICENSE.md`, mentioning what files it applies to if the rest of your package uses a different license. It can also be useful to mention at the top of the relevant files that they are using this license, but that's not a requirement.

Though note that if you're only using ideas, the license might not apply, e.g. if the algorithm is standard and documented elsewhere. It really depends.

**Comment by ararslan** [comment]
Often when code from Base Julia is moved into a package, the files typically contain a comment such as this at the top of the file:
```julia
# This code was formerly a part of Julia. License is MIT: http://julialang.org/license
```
If you're using _unmodified_ code from Distances, you could include something along the lines of
```julia
# This file contains code copied from the Distances.jl package.
# License is MIT: https://github.com/JuliaStats/Distances.jl/blob/master/LICENSE.md
```
at the top of those programs.

If you're only borrowing ideas and/or algorithms, you could add a comment to that effect somewhere in the README or in specific program files simply as a courtesy to the Distances.jl authors, but AFAIK that isn't a requirement of the MIT license.

One of the great things about the MIT license is that compliance with its terms is pretty easy. 🙂

**Comment by robertdj** [comment]
It's not unmodified code, but rather ideas. But I will at least include the lines that @ararslan suggests.
Thanks a lot for your help!

**Comment by ararslan** [comment]
I'm glad you've found Distances to be useful or otherwise inspiring. 🙂
