### ISSUE TITLE
Implement Haversine

### ISSUE THREAD

**Issue by prcastro** [JuliaStats/Distances.jl#71]
Haversine is a very useful distance when dealing with geospatial data. It is implemented in libraries such as scikit-learn, and it's pretty stardard today.

**Comment by ararslan** [comment]
Thanks for the suggestion, @prcastro, that's a good idea. Would you be willing to submit a PR to include it?

**Comment by prcastro** [comment]
Yes I would, however, looking at the code, I don't know where it's fit. While Haversine is a metric, it is a map like 

(XxY) x (XxY) -> [0, inf)

Different from, say, euclidean, that is X x X ->[0, inf). Therefore I don't know if it belongs to the `metrics.jl` file or not. Also, I don't know what API I am supposed to provide (i.e. what functions I must implement to be able to get haversine merged).

**Comment by juliohm** [comment]
I have the Haversine distance implemented in GeoStats.jl: https://github.com/juliohm/GeoStats.jl/blob/master/src/distances.jl#L107-L142

Can I submit a pull request @ararslan? Also, can I submit another PR for the EllipsoidDistance that you can find in the same file? This is basically Mahalanobis with a matrix that represents rotation+scaling.

It would be great to have Distances.jl as a dependency. I can work on this by the end of the week.
