### ISSUE TITLE
Implement Bray-Curtis dissimilarity?

### ISSUE THREAD

**Issue by kescobo** [JuliaStats/Distances.jl#75]
[Bray-Curtis](https://en.wikipedia.org/wiki/Bray%E2%80%93Curtis_dissimilarity) is a semi-metric often used in ecology.

The implementation for two vectors i and j is pretty straightforward:

```julia
function braycurtis(i::AbstractVector, j::AbstractVector)
    length(i) == length(j) || error("Vectors must be same length")
    return sum(abs.(i .- j))/sum(i .+ j)
end
```

I was looking around in the source code, and I'd be happy to try to submit a PR but I'm not entirely confident I understand what's going on with all of the` @inbounds` and `@eval` stuff...

**Comment by kescobo** [comment]
Actually, I [gave it a shot](https://github.com/kescobo/Distances.jl/tree/braycurtis) by copying the form of the Jaccard code, and it works! I'm not sure what the `@eval_reduce` block does, so I left that alone, but I tested it against some of my data and it seems to work as expected for two vectors and for `pairwise()`. 

Please let me know if you'd be interested in a PR.

**Comment by ararslan** [comment]
Yeah, a PR would be great!
