### ISSUE TITLE
Ellipsoid distance

### ISSUE THREAD

**Issue by juliohm** [JuliaStats/Distances.jl#78]
The Mahalanobis distance is very useful when we have a covariance/precision matrix to weight the observations. In many other applications where a covariance doesn't exist, however; we still have the opportunity to introduce a geometrical view by constructing a matrix based on rotation and scaling of the system axes.

The Ellipsoid distance I implemented  in GeoStats.jl does exactly this: https://github.com/juliohm/GeoStats.jl/blob/master/src/distances.jl#L38-L105

It is basically a helper constructor that given directions and scaling coefficients, builds the corresponding Mahalanobis matrix. Can I submit a PR that adds this distance to the package? My plan is to just reuse the code for Mahalanobis. The new struct Ellipsoid would just contain a Mahalanobis that is initialized properly.

Please let me know if that is welcome, and I will work on it during the week.

**Comment by Nosferican** [comment]
Would that include Vincenty Ellipsoid distance?

Vincenty, T. 1975. [Direct and inverse solutions of geodesics on the ellipsoid with application of
nested equations](http://www.movable-type.co.uk/scripts/latlong-vincenty.html). Survey Review Vol. 23, No. 176, pp 88-93.

**Comment by juliohm** [comment]
Thank you @Nosferican for introducing the Vincenty ellipsoid distance, I've never used it myself. The distance I implemented in the PR above is simply a rotation and scaling of the Euclidean ball. It is useful for imposing anisotropy during statistical estimation/simulation as demonstrated in this notebook: http://nbviewer.jupyter.org/github/juliohm/GeoStats.jl/blob/master/examples/AnisotropicModels.ipynb

In the context of lat/lon values, I've added the Haversine distance to this package. It should be less accurate, but perhaps useful to you?

Please feel free to give feedback on the PR, it is ready for review.

**Comment by Nosferican** [comment]
For most applications the Haversine distance should be good enough. I have used Vincenty ellipsoid distance when the area of study is relative small. Using few counties or precinct level data with a local datum (e.g. state level). I would have to look at the definition more carefully, but there is an implementation in R’s geosphere packarage which could be used to implement it here. Since the distance is more computationally intensive than Harvesine, it would be nice to have it here.
