### ISSUE TITLE
UndefVarError: Haversine not defined

### ISSUE THREAD

**Issue by zahachtah** [JuliaStats/Distances.jl#92]
Not sure if I am making something wrong?

```julia
   x₁ = rand(2)
    x₂ = rand(2)
    x₃ = rand(2)

    evaluate(Haversine(6371.0), x₁, x₂, x₃)

or 

 evaluate(Haversine(6371.0), x₁, x₂)
```
gives

```
UndefVarError: Haversine not defined

Stacktrace:
 [1] include_string(::String, ::String) at ./loading.jl:522
```
on both my local installation as well as juliabox but 

```julia
 evaluate(Euclidean(), x₁, x₂)
```
works. Not sure whats going on. Ideas appreciated.

**Comment by ararslan** [comment]
Looks like there hasn't been a new tag since Haversine support landed in master.

**Comment by ararslan** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/14078

**Comment by zahachtah** [comment]
:-D

Thanks
